name: C Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        choco install cmake -y
        choco install mingw -y
    
    - name: Create and Config
      run: |
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" ..
    
    - name: Build
      run: |
        cd build
        mingw32-make
        if %ERRORLEVEL% == 0 (
          echo "Build successful"
        ) else (
          echo "Build failed"
          exit 1
        )
